name: Release Devcontainer Feature
on:
  push:
    branches:
      - refactor/home-setup
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: src
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
